DROP TABLE EVENT IF EXISTS;
 
CREATE TABLE EVENT  (
    ID VARCHAR(20),  
	EVENTSTARTTIME VARCHAR(100),  
	EVENTENDTIME VARCHAR(100),  
	EVENTDURATION VARCHAR(100),  
    EVENTTYPE VARCHAR(100),
	EVENTHOST VARCHAR(100), 
	ALERT VARCHAR(100) 
	
) ;